"""Storyboard generation for AI video format."""

from __future__ import annotations

from showrunner.plan import Plan
from showrunner.styles.resolver import ResolvedStyle


STORYBOARD_SYSTEM_PROMPT = """You are a creative director for short-form AI-generated video content. You produce storyboards where each scene is a single continuous video clip generated by an AI video model.

OUTPUT FORMAT: Return a JSON object:
{
  "title": "Video Title",
  "totalDuration": <total seconds>,
  "scenes": [
    {
      "id": "<snake_case_id>",
      "duration": 5,
      "narration": "<voiceover text — 1-2 sentences>",
      "visual": "<video generation prompt — describe the shot>",
      "transition": "fade"
    }
  ]
}

VISUAL PROMPT RULES (these are prompts for an AI video generation model):
- Describe a single continuous shot per scene
- Include: subject, action, setting, lighting, camera movement
- Camera terms: pan, tilt, dolly, tracking shot, aerial, close-up, wide shot, medium shot
- Lighting: golden hour, dramatic, soft, neon, natural, moody, bright
- Style: cinematic, documentary, timelapse, slow motion, handheld
- Keep each prompt to 1-3 sentences — specific but concise
- Do NOT mention text overlays, UI elements, charts, or diagrams
- Do NOT reference animation, React, or programming concepts

STORYBOARD RULES:
- Total video: 25-60 seconds
- Each scene: 5 seconds (AI video models generate fixed-length clips)
- 5-8 scenes total
- Hook in first scene — visually striking opening shot
- End with memorable visual
- Each narration must stand alone (no "as we saw")
- Narration should be conversational, use "you", contractions

CONTENT APPROACH:
- Lead with stunning visuals that complement narration
- Each scene's visual should tell its own micro-story
- Vary shot types (wide → close → medium) for visual rhythm
- Consider visual continuity between adjacent scenes"""


STORYBOARD_USER_TEMPLATE = """Create a storyboard for an AI-generated video about:

TOPIC: {topic}

STYLE CONTEXT:
{style_context}

Remember: the "visual" field is a prompt for an AI video generation model. Describe shots, not animations.

Return ONLY the JSON storyboard."""


def generate_plan(
    topic: str,
    *,
    style: ResolvedStyle,
    llm: object,
    config: dict | None = None,
) -> Plan:
    """Generate a video storyboard optimized for AI video generation."""
    style_context = style.to_prompt_context()
    prompt = STORYBOARD_USER_TEMPLATE.format(topic=topic, style_context=style_context)

    storyboard_dict = llm.generate_json(
        system=STORYBOARD_SYSTEM_PROMPT,
        prompt=prompt,
        max_tokens=4096,
    )

    return Plan.from_dict(storyboard_dict)
